spring.application.name=sb-ecom

server.port = 8082
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=postgres

project.images = images/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName = sbEcom



logging.level.org.springframework=info
logging.level.org.hibernate.SQL=info
logging.level.org.springframework.security=info
logging.level.com.project.example=info

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile



